#!/bin/bash

dir_name=$(dirname "$0")
tasks_raw=$(cat $dir_name/todo.txt)
tasks_array=();
done_code="<fc=#B2FBA4>x</fc>"
undone_code="<fc=#FBA4A8>x</fc>"

for i in $tasks_raw; do
    tasks=$(echo "$i" | cut -d '=' -f 1)
    tasks_status=$(echo "$i" | cut -d '=' -f 2)

    if [[ $tasks_status = 0 ]]; then
        tasks_status=$undone_code
    else
        tasks_status=$done_code
    fi
    tasks_array=("${tasks_array[@]}" "$tasks: $tasks_status");
done

echo "${tasks_array[@]}"
